### ISSUE TITLE
Remove taktik references and allow to build on own servers

### ISSUE THREAD

**Issue by ehealthplatformstandards** [ehealthplatformstandards/laboResultVisualizationAPI#1]

**Comment by bdc-ehealth** [comment]
@jmp-ehealth, @ec-ehealth,

I modified the gradle build script to get the business code from github, instead of the taktik maven repository (see https://github.com/ehealthplatformstandards/laboResultVisualization/issues/22 ). I also removed all taktik specific gradle commands and (tried to) replace them with publicly available plugins for the creation of the docker image.

**Comment by bdc-ehealth** [comment]
this is the commandline to run the docker: docker run -p 8912:8912 be.fgov.ehealth/ehealth-fhirviz:&lt;version&gt;
